name: Run

on:    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install DotNet v6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: Run
        run: |
          dotnet run -c Release
